// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import StackbiblioController from "./stackbiblio_controller"
application.register("stackbiblio", StackbiblioController)

import SyncerController from "./syncer_controller"
application.register("syncer", SyncerController)
