// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnnotationController from "./annotation_controller"
application.register("annotation", AnnotationController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import ImportController from "./import_controller"
application.register("import", ImportController)

import StackbiblioController from "./stackbiblio_controller"
application.register("stackbiblio", StackbiblioController)

import SubmissionController from "./submission_controller"
application.register("submission", SubmissionController)

import SyncerController from "./syncer_controller"
application.register("syncer", SyncerController)

import TabController from "./tab_controller"
application.register("tab", TabController)
