require: rubocop-rails
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/LineLength:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
AllCops:
  NewCops: enable